import type { SandpackFiles, SandpackPredefinedTemplate } from "@codesandbox/sandpack-react";

/** The two languages a submission can be written in; transpiled to JS server-side before running. */
export type SupportedLanguage = "javascript" | "typescript";

/** Display names for each language — the language toggle and "shown in X" fallback notice. */
export const LANGUAGE_LABELS: Record<SupportedLanguage, string> = {
  typescript: "TypeScript",
  javascript: "JavaScript",
};

export type Difficulty = "easy" | "medium" | "hard";

/** Which test set a submission runs against: Run hits the exposed examples, Submit adds the hidden set. */
export type RunMode = "run" | "submit";

/**
 * Topic taxonomy, single-sourced from the catalog's `topicTags` slugs
 * ([leetcodeProblemSet.json](./problems/leetcodeProblemSet.json)). Authored problems pick from
 * this union so a tag can't be invented that the filter UI won't know about. Grow it as new tags
 * surface in imported problems — see [problem-authoring.md](../../docs/features/problem-authoring.md).
 */
export type TopicTag =
  | "array"
  | "string"
  | "dynamic-programming"
  | "math"
  | "two-pointers"
  | "backtracking"
  | "hash-table"
  | "linked-list"
  | "matrix"
  | "recursion"
  | "sorting"
  | "binary-search"
  | "stack"
  | "tree"
  | "binary-tree"
  | "bit-manipulation"
  | "simulation"
  | "depth-first-search"
  | "greedy"
  | "binary-search-tree"
  | "sliding-window"
  | "divide-and-conquer"
  | "monotonic-stack"
  | "trie"
  | "heap-priority-queue"
  | "merge-sort"
  | "string-matching"
  | "combinatorics"
  | "memoization"
  | "breadth-first-search"
  | "graph"
  | "union-find"
  | "queue"
  | "interval"
  | "prefix-sum";

/** One test case, generic over the solution's argument tuple and its return type. */
export type TestCase<Args extends unknown[], Result> = {
  name?: string;
  args: Args;
  expected: Result;
};

/** A worked example: a visible test case plus prose explaining the output. The visible run set is built from these. */
export type Example<Args extends unknown[], Result> = TestCase<Args, Result> & {
  explanation?: string;
};

/**
 * How a param/result is materialized before/after the call, so test data stays plain arrays while the
 * solution sees the real reference type:
 * - `"value"` (default) — passed straight through.
 * - `"linked-list"` — an array hydrates into a `ListNode` chain in; the returned chain flattens back out.
 * - `"binary-tree"` — a LeetCode level-order array (with `null` gaps) hydrates into a `TreeNode` in; the
 *   returned tree serializes back to the same level-order array (trailing `null`s trimmed).
 * - `"linked-list[]"` / `"binary-tree[]"` — the array variants: an array *of* arrays maps element-wise
 *   (e.g. merge-k-sorted-lists takes a `ListNode[]`; "generate all BSTs" returns a `TreeNode[]`).
 */
export type IoShape = "value" | "linked-list" | "linked-list[]" | "binary-tree" | "binary-tree[]";

export type ProblemIo = {
  params?: IoShape[];
  result?: IoShape;
};

/** Where a problem came from — kept for re-sync and difficulty calibration, not shown to the solver. */
export type ProblemSource = {
  /** `"leetcode"` for catalog-sourced rows; `"authored"` for off-catalog / build problems with no catalog row. */
  origin: "leetcode" | "authored";
  /** `questionFrontendId` from the catalog; omitted for off-catalog `"authored"` problems. */
  frontendId?: string;
  /** Acceptance rate at import time (0–1) — a difficulty sanity check. */
  acRate?: number;
  /** Authoring confidence (0–1) when generated by the import agent; omitted for hand-authored problems. */
  confidence?: number;
};

/**
 * The seed metadata an importer starts from — the only fields copied from a source, with everything
 * else authored. Derived from `ProblemBase` so it can't drift from the problem shape. Produced by
 * [resolveProblem.mjs](../../scripts/resolveProblem.mjs) for catalog rows (`origin: "leetcode"`), or
 * assembled from a web lookup for off-catalog problems (`origin: "authored"`).
 */
export type ProblemStub = Pick<ProblemBase, "id" | "title" | "difficulty" | "tags"> & {
  source: ProblemSource;
};

/** One published approach in the Solutions tab: a named write-up plus per-language code. */
export type ProblemSolution = {
  name: string;
  explanation: string;
  code: Partial<Record<SupportedLanguage, string>>;
};

/** The `kind` discriminant. `"algo"` is the pure-function judge; `"build"` is a pad-backed sandbox task. */
export type ProblemKind = "algo" | "build";

/** Fields every problem carries, regardless of kind. The shared spine of the discriminated union. */
export type ProblemBase = {
  id: string;
  /**
   * Permanent 1-based catalog number shown as `#NN` and used as the newest/oldest sort axis. Assigned
   * once and never reused, so reordering or back-filling the bank can't renumber other problems. New
   * problems take `max(existing) + 1`; `verifyProblems` rejects duplicates (gaps are fine — a removed
   * problem's number isn't recycled).
   */
  number: number;
  title: string;
  difficulty: Difficulty;
  tags: TopicTag[];
  prompt: string;
  source?: ProblemSource;
};

/**
 * An algorithm problem, generic over the solution signature `(...args: Args) => Result`. The
 * signature drives the case types: every `args` tuple and `expected` is checked against it.
 *
 * - `examples` are the visible cases (Run uses them; they render in the Description tab).
 * - `hiddenTests` are server-only — they never cross into `ClientProblem`, so the inputs that probe
 *   robustness aren't shipped to the browser. Submit adds them.
 * - `checker` (server-only) overrides deep-equal for problems with multiple valid answers.
 */
export type AlgoProblem<Args extends unknown[] = unknown[], Result = unknown> = ProblemBase & {
  kind: "algo";
  /** Input-bound statements, rendered as a list; also tell the author how to size scale tests. */
  constraints: string[];
  /** The function the harness calls. The user's source must declare a function of this name. */
  functionName: string;
  starterCode: Record<SupportedLanguage, string>;
  examples: Example<Args, Result>[];
  hiddenTests: TestCase<Args, Result>[];
  /** Per-param / result hydration; omit for plain-value problems. */
  io?: ProblemIo;
  /**
   * JS arrow-function source `(actual, args, expected) => boolean`, run in the worker to validate
   * answers that aren't a single fixed value. `args` is the argument list **as the function received
   * it, after the call returns** — so it carries any in-place mutation, letting a checker score the
   * mutated input (`sort-colors`) or assert the result is the same instance (`actual === args[0]`).
   * Omit for exact deep-equal match.
   */
  checker?: string;
  solutions?: ProblemSolution[];
};

/**
 * A build problem: open-ended, human-evaluated, solved in a pad-backed Sandpack sandbox rather than
 * graded by the worker. `evaluationNotes` is the rubric a reviewer reads — there is no pass/fail
 * oracle. The pad seeding from `template`/`files` lands in a later phase; see
 * [company-sourcing.md](../../docs/features/company-sourcing.md).
 */
export type BuildProblem = ProblemBase & {
  kind: "build";
  template: SandpackPredefinedTemplate;
  files: SandpackFiles;
  evaluationNotes?: string[];
};

/** Either kind of problem. Narrow on `kind` before touching kind-specific fields. */
export type AnyProblem = AlgoProblem | BuildProblem;

/**
 * The header bits resolved *outside* the problem module (server-side in the route) and threaded to the
 * workspaces → `ProblemTitleBar`: the catalog `number` and the company associations from `companies.ts`.
 */
export type ProblemHeaderData = {
  number: number;
  companies: readonly string[];
};

/** The client-safe projection of an algo problem: drops the server-only hidden tests and answer-checker. */
export type ClientProblem<Args extends unknown[] = unknown[], Result = unknown> = Omit<
  AlgoProblem<Args, Result>,
  "hiddenTests" | "checker"
>;

/**
 * Author an algo problem with the solution signature pinned, so case `args`/`expected` are
 * type-checked against it: `defineAlgoProblem<[number[], number], number[]>({ … })`. `kind: "algo"` is
 * injected here, so authored modules never spell it out.
 */
export const defineAlgoProblem = <Args extends unknown[], Result>(
  problem: Omit<AlgoProblem<Args, Result>, "kind">,
): AlgoProblem<Args, Result> => ({ kind: "algo", ...problem });

/** Author a build problem. `kind: "build"` is injected, mirroring `defineAlgoProblem`. */
export const defineBuildProblem = (problem: Omit<BuildProblem, "kind">): BuildProblem => ({
  kind: "build",
  ...problem,
});

/**
 * Best-effort parameter names pulled from the JS starter signature, so the Testcase/Input
 * views can label args (`nums =`) like LeetCode. Falls back to positional `arg N` labels when
 * the signature can't be parsed cleanly (e.g. destructured params), guarded on the arity match.
 */
export const deriveParamNames = (source: string, functionName: string, arity: number): string[] => {
  const fallback = Array.from({ length: arity }, (_, index) => `arg ${index + 1}`);
  const match = source.match(new RegExp(`${functionName}\\s*\\(([^)]*)\\)`));
  if (!match) return fallback;
  const names = match[1]
    .split(",")
    .map((part) => part.split(":")[0].trim())
    .filter(Boolean);
  return names.length === arity ? names : fallback;
};

/**
 * The wire shape the runner reports back per test case. For hidden cases the runner masks
 * `expected`/`actual`/`logs` (they'd leak the probing inputs) — only pass/fail, error, and timing survive.
 */
export type TestResult = {
  name: string;
  passed: boolean;
  expected: unknown;
  actual: unknown;
  logs: string[];
  error: string | null;
  ms: number;
  hidden: boolean;
};

export type SubmissionOutcome =
  | { status: "ok"; results: TestResult[] }
  | { status: "compile-error"; message: string }
  | { status: "timeout"; ms: number }
  | { status: "crashed"; message: string };
